### ISSUE TITLE
ShortDescription remark

### ISSUE THREAD

**Issue by michellzappa** [envisioning/tdb#100]
It's preferable if ShortDescription for Technologies is NOT mandatory.
Instead, the UI should show the LongDescription truncated to X characters if ShortDesc = empty.
This will help our workflow ;)

**Comment by arthursoares** [comment]
+1 for this. @rafaelcorreiapoli

**Comment by rafaelcorreiapoli** [comment]
Should I ignore markdown when truncating ?
longDescription: ## This is a header
shorDescription will be "This is a"

**Comment by rafaelcorreiapoli** [comment]
Done here 9ad83577d8dbdee0a3299c6acbd1098b4018848f
We just need to set the value of X
```
const SHORT_TEXT_TRUNCATE_AT = 10;
```

**Comment by rafaelcorreiapoli** [comment]
It first strips the markdown, and then truncates the plain text at a given position...
```
    if (doc.description && Array.isArray(doc.description)) {
      doc.description = _.map(doc.description, (desc) => {
        if (!desc.shortText && desc.longText) {
          let noMarkdown = removeMarkdown(desc.longText) || '';
          desc.shortText = noMarkdown.substring(0, SHORT_TEXT_TRUNCATE_AT);
        }
        return desc;
      });
    }
```

**Comment by arthursoares** [comment]
@rafaelcorreiapoli Yes, truncate markdown. Make it 144 chars. :)

**Comment by rafaelcorreiapoli** [comment]
Done 52abfb39fddecb3fc23a8abcc81e8ba739729feb with 144 characters
