### ISSUE TITLE
Hangouts 03/03/2016

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/tdb#106]
Pontos discutidos: 

1. Todos os formulários devem possuir todas as propriedades do schema para serem editadas. Formulários de Add e Edit devem possuir inclusive os attachments e ser possível criar as relações com as outras entidades.
2. Combinamos de fazer reuniões semanais assim que o Arthur voltar para aumentar as interações, feedbacks e melhorar a comunicação das equipes.
3. Também foi combinado que assim que uma issue for fechada e publicada em ambiente de staging, a equipe da envisioning irá testar se tudo funciona conforme o esperado, e já dar feedbacks e sugerir ajustes se necessário.
4. Precisamos montar uma estrutura para facilitar o desenvolvimento dos componentes, com build mais rápido e que mantenha os projetos atualizados.

- Esqueci de alguma coisa? @arthursoares @rafaelcorreiapoli 

Valeu galera! :+1:

**Comment by lnmunhoz** [comment]
@arthursoares Criamos o repositório com os arquivos less isolados. Você consegue integrar com o seu compilador? https://github.com/envisioning/tdb-ui

**Comment by arthursoares** [comment]
1. Correto.
2. Sim!
3. Vocês podem dar um comment no Issue ou criar um issue pedindo o feedback.
4. (Y). A ideia é não parar o desenvolvimento.

Sobre o compilador, vou testar amanhã e te reporto! :) valeu

**Comment by michellzappa** [comment]
Can we close this issue?
