### ISSUE TITLE
Big images on cards not showing correctly

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/tdb#108]
We need "zoom out" images like this on cards to fetch properly.
![liontax-baixe-o-guiia-2016_03](https://cloud.githubusercontent.com/assets/4376835/13618661/27feeaea-e564-11e5-9a0a-6e0f11ed1f71.jpg)

**Comment by rafaelcorreiapoli** [comment]
http://cloudinary.com/documentation/image_transformations

**Comment by rafaelcorreiapoli** [comment]
If we show the entire image, we may lose our desired aspect ratio and our cards will be deformed

**Comment by rafaelcorreiapoli** [comment]
![solve](https://cloud.githubusercontent.com/assets/12840136/13628700/0acc978e-e5b3-11e5-9273-57dcb2e3bc53.png)

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz is is fixed? can we close it?

**Comment by lnmunhoz** [comment]
@rafaelcorreiapoli You make this change for the white background? If yes can close it!

**Comment by rafaelcorreiapoli** [comment]
Yes, as it is on the printscreen
