### ISSUE TITLE
E-mail branding

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#116]
<img width="582" alt="screen shot 2016-03-09 at 9 07 43 pm" src="https://cloud.githubusercontent.com/assets/533339/13655015/10e76bf2-e63b-11e5-96ae-d0c5854c816a.png">

We need to customize the e-mail subject, body and format to match TDB's.

**Comment by lnmunhoz** [comment]
I think this should have the `design` label instead of `bug`, right?

**Comment by arthursoares** [comment]
@lnmunhoz sorta, no user knows what "Meteor" is, neither that they have an account there. So this is a bug. Users will probably add it to Spam or delete without knowing what the file really is.

**Comment by michellzappa** [comment]
+1 Arthur. It's not a design issue in particular.

**Comment by rafaelcorreiapoli** [comment]
Can you give us the email template? with images, texts...

**Comment by michellzappa** [comment]
Just have to change email headers! Replace Meteor with Envisioning, and
@Meteor.com with @envisioning.io.

**Comment by lnmunhoz** [comment]
36c90b9ccb018722993e75c7328c36e0af1315ae
