### ISSUE TITLE
Search: No need to load all items at start

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#122]
![screen shot 2016-03-11 at 1 19 54 pm](https://cloud.githubusercontent.com/assets/533339/13702033/02b46d76-e78c-11e5-85e5-c27a2cd8d948.png)

There is no need to load all cards prior to executing a search. This takes a load on the user's browser.

**Comment by rafaelcorreiapoli** [comment]
I know, I will implement infinite loading

**Comment by lnmunhoz** [comment]
@michellzappa @arthursoares 
![cvou36kww6](https://cloud.githubusercontent.com/assets/4376835/13817511/40b8adba-eb71-11e5-9367-b9d059202594.gif)

**Comment by michellzappa** [comment]
Perfect!

**Comment by michellzappa** [comment]
Also, this page should be landing/start page for logged in users.
