### ISSUE TITLE
Hangouts 11/03/2016 - Hotfixes

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/tdb#124]
- [x] longText no contextualDescription (usar markdown também)
- [x] Menu: clique vai direto pro dashboard, botão de add dentro do Dashboard
- [x] Project: Type assume os valores [Prospect, Open, Closed]
- [x] Attachment: remover tag e colocar Type -> [?, ?, ?] @arthursoares preciso das opções
- [x] verificar logs elasticsearch, por que ta caindo?
- [x] breadcrumb -> tirar "Dashboard"
- [x] Project -> evId primeiro campo
- [x] briefCards -> link na foto também
- [x] upload file -> mostrar imagem atual com opcao pra tirar
- [x] aboutBox de todas entities-> arrumar link do edit modal
- [x] uploadAttachment-> upload do arquivo no change do input, nao só quando clica
- [x] bug de download do arquivo (attachment)
- [x] aboutBox de todas entities -> parametros de processamento do cloudinary (qual o AR? @arthursoares)
- [x] technologies-> campo Id auto increment de 4 digitos gerado no servidor
- [x] technologiesEdit -> server devolveu 500 no staging
- [x] Bug do autoform que guardava valores removidos de um array como null's no mongo
- [x] Mostrar imagens cadastrar para a tecnologia no formulário de edição (subscribe)
- [x] Tratar imagens não encontradas no briefCard
- [x] Colocar mensagem "Under construction" nas páginas que não estão previstas para o Milestone 01

**Comment by michellzappa** [comment]
*breadcrumb

**Comment by michellzappa** [comment]
Awesome list. Great features. Thanks for this!

**Comment by rafaelcorreiapoli** [comment]
@arthursoares  @michellzappa 
Tem algo errado. Attachments é pra ter a type mas não é [Prospect, Open, Closed] pois não faz sentido hahaha
Podem me passar quais são os tipos do Attachment?

o [Prospect, Open, Closed] é do Projects, certo ?

**Comment by michellzappa** [comment]
Sim, faz mais sentido assim.

**Comment by lnmunhoz** [comment]
> technologies-> campo Id auto increment de 4 digitos gerado no servidor

Done here 04020932dcdfb9d6dc9c0a6ed87fe36b6e8cbbcc

**Note**: The field `techId` is an integer in the database. We should format the 4 digits in the client.

**Comment by lnmunhoz** [comment]
> Menu: clique vai direto pro dashboard, botão de add dentro do Dashboard

Done here b3c09bd1c8b4151ff0598564eb73acc9a8085844

**Comment by arthursoares** [comment]
@rafaelcorreiapoli

attachments can be:

Article, Whitepaper, News, Product page, Media.

**Comment by lnmunhoz** [comment]
> Attachment: remover tag e colocar Type -> [?, ?, ?] @arthursoares preciso das opções

Done here b98c067f3af7de544a35fc59517d301d64ec09b4

**Comment by lnmunhoz** [comment]
> - upload file -> mostrar imagem atual com opcao pra tirar
-  uploadAttachment-> upload do arquivo no change do input, nao só quando clica

Done here d031037b096e8896c3b4227bf26a7f30c402aeef

**Comment by lnmunhoz** [comment]
@arthursoares I remember that searches in general should not display any result by default. I'm right?

**Comment by michellzappa** [comment]
No results should be shown before user has started typing into textbox.

**Comment by lnmunhoz** [comment]
Thanks @michellzappa

**Comment by rafaelcorreiapoli** [comment]
TechId now is saved as a padded string
0001, 0002...
9de6e8708f611edb886e41e62c16c971550e512d

**Comment by lnmunhoz** [comment]
> Colocar mensagem "Under construction" nas páginas que não estão previstas para o Milestone 01

Instead of this I remove the routes and the links for them.

**Comment by lnmunhoz** [comment]
Closing! BAM!
