### ISSUE TITLE
Markdown longtext field

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#134]
<img width="934" alt="screen shot 2016-03-17 at 11 13 17 am" src="https://cloud.githubusercontent.com/assets/533339/13842979/631beba4-ec31-11e5-8401-a9109837bab1.png">

I'd love if we could just mimic Github's entry field. (This exact window). Two columns take way to much space. If it is too complicated to add a "preview" tab, just make one with plain text. Also, buttons like "**B**" or "*i*" are better, IMHO, than `**bold**` and `*italic*`.

<img width="710" alt="screen shot 2016-03-17 at 11 14 35 am" src="https://cloud.githubusercontent.com/assets/533339/13842994/72e17680-ec31-11e5-8f48-2cd333bb765c.png">

**Comment by arthursoares** [comment]
This is ok, right? Since this component will be reused everywhere.

**Comment by michellzappa** [comment]
+1

**Comment by arthursoares** [comment]
Não consigo testar. #262 e #263
