### ISSUE TITLE
technologyDashboard update

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#136]
<img width="1440" alt="screen shot 2016-03-17 at 1 50 37 pm" src="https://cloud.githubusercontent.com/assets/533339/13846427/40b203e4-ec47-11e5-953b-ed2372887378.png">

This should be the guideline for dashboards. The two latest commits to gh-pages have the code: 405a055c5db11c0a46bc513519eea0e929ec9d95 & eb1146f5630c611032daaa850967f8557aefb46e 

- Cleaner activity log (we've been emphasizing the wrong information). Also added relative time.

Let's discuss this :)

**Comment by arthursoares** [comment]
- [ ] Every dashboard page with the card + search box, will display the latest created or updated technologies. 

- [ ] When the searchbox gets focus, scroll the page down to it.

<img width="1280" alt="screen shot 2016-03-30 at 1 06 05 am" src="https://cloud.githubusercontent.com/assets/533339/14126767/ada6628a-f613-11e5-89f2-bf9720f54bef.png">

**Comment by arthursoares** [comment]
(This is looking amazing)

**Comment by rafaelcorreiapoli** [comment]
Sorry, i didn't understand
"Every dashboard page with the card + search box, will display the latest created or updated technologies."

**Comment by arthursoares** [comment]
@rafaelcorreiapoli havíamos mudado o comportamento do box de search. Ele era para aquela página padrão de search, que abria com cartas de tech, projetos, etc… O que estou propondo é que no dashboard de cada área, já abra com as últimas cartas atualizadas/criadas. 

Abriu technologies, vão aparecer as últimas cartas de technologies.
Organizations, Attachments e projects.

**Comment by rafaelcorreiapoli** [comment]
Você diz para mostrar por padrão as últimas entidades inseridas/modificadas ao invez de não mostrar nada (quando o search input está vazio)

**Comment by arthursoares** [comment]
Isso. Logo quando carrega a página de dashboard.

https://tdb-design.herokuapp.com/technologyDashboard.php 

Repara que o padding tá diferente entre colunas. Deve estar faltando uma declaração que vai aqui:
https://github.com/envisioning/tdb/blob/gh-pages/footer.php

```html
<style>
.cards-box {
    margin: 0 auto;
}
.cards-box .ibox {
    margin-bottom: 0;
}
.cards-item {
    margin-bottom: 15px;
}
</style>
<script>
$(window).load(function() {
    $('.cards-box').masonry({
        // options
        columnWidth: '.cards-size',
        gutter: 15,
        percentPosition: true
    });
});
</script>
```

- [ ] Também está faltando o ShortDescription nas cartas

**Comment by rafaelcorreiapoli** [comment]
Ah, beleza! é que ainda não implementamos o Masonry #170, mas foi bom ter avisado! quando implementarmos vou lembrar de colocar esses parâmetros :)

**Comment by rafaelcorreiapoli** [comment]
@arthursoares, não é que está faltando, é que todas as tecnologias estão com a description em Draft, então é como se não tivesse. Mudei a do "Aerogel" pra Published
