### ISSUE TITLE
Add permalinks for social networks on user profile

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/tdb#143]
We can add our usernames but there's not a permalink to the profile page.
Example [here](http://tdbstaging-59484.onmodulus.net/users/Ffwn9g8HY98kFnXtc/entry).

**Question**: Should be added just the username or the url?

**Comment by arthursoares** [comment]
Add the permalink.

**Comment by michellzappa** [comment]
Not worth the trouble.
