### ISSUE TITLE
mainDashboard update

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#145]
Revised design, featured at: https://tdb-design.herokuapp.com/index.php
## ToDo

- [x] Correct text for other boxes.

#144

**Comment by lnmunhoz** [comment]
For organizations should display totals for `academic`, `non-profit`, `governamental` and `private`?

**Comment by arthursoares** [comment]
@lnmunhoz not really necessary. I'll delete this image. It is deprecated. Check the URL
https://tdb-design.herokuapp.com/index.php
