### ISSUE TITLE
cards for Technologies, Attachments, Organizations & Attachments

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#150]
<img width="1418" alt="screen shot 2016-03-22 at 5 14 34 pm" src="https://cloud.githubusercontent.com/assets/533339/13960903/1d328bbe-f052-11e5-8962-49aa86ec56bf.png">

Revised design for #11 and every other card on the system. This should be the default when showing listings and search results. User cards is not listed, will create another issue on the subject.

Any doubts on this functionality?

Code is here: https://github.com/envisioning/tdb/blob/b026e4a4f1441325bda8e147a760e4064cd654e8/attachmentCard.php

Added support for masonary on 8feada7

**Comment by rafaelcorreiapoli** [comment]
As I understand they may vary size, then we will use Masonary to fix the grid, correct?

**Comment by arthursoares** [comment]
Yes. check latest commits and https://tdb-design.herokuapp.com

**Comment by rafaelcorreiapoli** [comment]
Which version is more updated? this one or 
https://tdb-design.herokuapp.com/cards.php
?

**Comment by arthursoares** [comment]
@rafaelcorreiapoli for all issues on UX, the tdb-design is the most recent and up-to-date / gh-pages branch.

**Comment by rafaelcorreiapoli** [comment]
Ok. Another thing:
the technology card is using a class called card-id.. I found it here, on this minified file:
https://github.com/envisioning/tdb/blob/gh-pages/stylesheets/main.css
(and it was very hard to find :P)
Please try to put all stylings of some component on a single file, then it will be easier to import it to Meteor's version
BTW, nice work!

**Comment by arthursoares** [comment]
As I've mentioned to @lnmunhoz and at #161 just import the stylesheets from gh-pages. It was created from a package lucas built for me.

https://github.com/envisioning/tdb/blob/gh-pages/stylesheets/elements/technologyCard.less the ID is here.

and here is the folder https://github.com/envisioning/tdb/blob/gh-pages/stylesheets/

**Comment by rafaelcorreiapoli** [comment]
Ops,  I was using this one
https://github.com/envisioning/tdb/blob/gh-pages/stylesheets/components/technology_card.import.less

**Comment by arthursoares** [comment]
can you just import the compiled css?

**Comment by rafaelcorreiapoli** [comment]
The text under the Name is the description's shortText or longText? Should I truncate it?

**Comment by arthursoares** [comment]
It is shortDescription.

**Comment by rafaelcorreiapoli** [comment]
But the search engine will keep searching on longText, right? What if the result is shown because of a word that is present on longText but is not present on shortDescription? the user won't have a "highlight" feedback on shortDescription... is it ok ?

**Comment by michellzappa** [comment]
That's OK!

**Comment by rafaelcorreiapoli** [comment]
#7 
Projects must have an ```image``` field, right?

**Comment by arthursoares** [comment]
Yes.

On Sat, Mar 26, 2016 at 8:03 AM, Rafael Ribeiro <notifications@github.com>
wrote:

> #7 <https://github.com/envisioning/tdb/issues/7>
> Projects must have an image field, right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/150#issuecomment-201721344>
>



-- 
http://arthur.wtf
+55 11 96960.6666

**Comment by rafaelcorreiapoli** [comment]
When #171 is finished, this can be closed
