### ISSUE TITLE
technologyEdit

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#163]
Available at:
https://tdb-design.herokuapp.com/technologyEdit.php

Already supporting versioning.

- [ ] Add message and latest update to Drafts

**Comment by rafaelcorreiapoli** [comment]
@arthursoares,
- How do we remove an Organization/Project/Attachment relation?
- When we click the "+" button on these entries, what happens exactly? I think that we can show a Modal with a search engine and a list to display results, is it ok?
- When we do one of these operations, the result is instantly saved to the database or the user must click on a Save button at the end ?

**Comment by arthursoares** [comment]
@rafaelcorreiapoli 
that should happen on the contextual/dropdown menus of each card. And use the ibox-toolbar of the category for Adding new ones.

<img width="1056" alt="screen shot 2016-04-05 at 5 34 43 pm" src="https://cloud.githubusercontent.com/assets/533339/14287847/bd273b1c-fb54-11e5-9d8b-1fca581c05c8.png">

**Comment by lnmunhoz** [comment]
Some questions @arthursoares: 
- When we do one of these operations, the result is instantly saved to the database or the user must click on a Save button at the end ? +1 @rafaelcorreiapoli

**Comment by arthursoares** [comment]
Confirmation modal and save on the operation.
"Are you sure you want to remove this attachment from Delivery Drones?"

On Thu, Apr 7, 2016 at 5:55 PM Lucas N. Munhoz <notifications@github.com>
wrote:

> Some questions @arthursoares <https://github.com/arthursoares>:
>
>    - When we do one of these operations, the result is instantly saved to
>    the database or the user must click on a Save button at the end ? +1
>    @rafaelcorreiapoli <https://github.com/rafaelcorreiapoli>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/163#issuecomment-206967349>
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by lnmunhoz** [comment]
@arthursoares An operation is any change in the current technology. So if a `tag` is added will pop up a modal. Not good...
Maybe we should just show a notification on top corner saying that the document was updated?

**Comment by arthursoares** [comment]
I think there are tiers of operations:

*adding a tag*: sure, not that important, you can go without checking.
*deleting a technology, removing an attachment or project: *modal.

On Thu, Apr 7, 2016 at 6:50 PM Lucas N. Munhoz <notifications@github.com>
wrote:

> @arthursoares <https://github.com/arthursoares> An operation is any
> change in the current technology. So if a tag is added will pop up a
> modal. Not good...
> Maybe we should just show a notification on top corner saying that the
> document was updated?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/163#issuecomment-206989664>
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by lnmunhoz** [comment]
Currently working on branch `technologiesEdit`

**Comment by lnmunhoz** [comment]
Hi @arthursoares!

In the Descriptions section, when I `publish` a description, the current published description its changed to `draft` or `review`?  We can can have just one published description by technology right?

**Comment by arthursoares** [comment]
Every technology will only have one `published` description (read: visible and enabled description). We can discuss which one is the best take one this. After you promote one to `Publish` should the previous one co-exist as `published`, but it will be listed afterwards because of the timestamp? Or would we need a second toggle/field, such as `Active description`.

What is your take on this one?

**Comment by lnmunhoz** [comment]
For instance after promote a description to `published` the current one is changed to `review`. The best implementation depends of envisioning workflow. This descriptions has two or more "published" versions? What you think @michellzappa ?

The active toggle is a good solution for that @arthursoares.

**Comment by michellzappa** [comment]
1. Keep it simple.
2. Art, confere com Thiara? Ela manja do workflow.

**Comment by lnmunhoz** [comment]
#### Todo Priority

- [] Simple markdown editor github like (without toolbox)
- [] New image component

#### Todo next
- [] Toolbox for the markdown editor
