### ISSUE TITLE
mainDashboard fixes

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#166]
<img width="1439" alt="screen shot 2016-03-28 at 9 54 22 am" src="https://cloud.githubusercontent.com/assets/533339/14073646/1cc488d0-f4cb-11e5-84a1-abe12665827a.png">

There are some padding issues with this layout.

- [x] Drop the "wrapper" class from this div.
<img width="1115" alt="screen shot 2016-03-28 at 9 55 39 am" src="https://cloud.githubusercontent.com/assets/533339/14073669/4d79802a-f4cb-11e5-849a-3f8e240d41aa.png">

- [x] Remove the top pathbar / breadcrumb

<img width="360" alt="screen shot 2016-03-28 at 9 56 45 am" src="https://cloud.githubusercontent.com/assets/533339/14073691/7733ddca-f4cb-11e5-8953-91b441c1462b.png">

- [x] Fix table also #161 

![screen-shot-2016-03-28-at-10 25 31-am](https://cloud.githubusercontent.com/assets/533339/14074227/c1f8b296-f4cf-11e5-9ec5-d1a62aa4a165.jpg)

**Comment by rafaelcorreiapoli** [comment]
It's already on staging, if it is correct now, please let me know so we can close the issue =)

**Comment by arthursoares** [comment]
Yep!
