### ISSUE TITLE
techEntry

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#17]
Placeholder issue for further development.
Reserving the issue ID to link with the visual UX map.

**Comment by michellzappa** [comment]
Is techEntry what we sometimes call the "Permalink" display? For viewing tech details?

**Comment by rafaelcorreiapoli** [comment]
@michellzappa Yes, sorry for the late reply

**Comment by arthursoares** [comment]
ToDo:
- [ ] improve image gallery. it sucks right now.
