### ISSUE TITLE
Masonry support on searchResults

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/tdb#170]
@lnmunhoz Let's use this as reference
https://github.com/Sewdn/meteor-infinite-search

**Comment by lnmunhoz** [comment]
Work in progress here c0e652b. Need to test all grid to see if nothing breaks.

**Comment by lnmunhoz** [comment]
@rafaelcorreiapoli I think the worst part is over. Closing...

![http://g.recordit.co/oVALerputR.gif](http://g.recordit.co/oVALerputR.gif)

**Comment by lnmunhoz** [comment]
Its working already but there's some **known issues**:
- If you type and delete very fast on the search input, masonry will bug and not fit items propertly.
