### ISSUE TITLE
Counting relations on Cards

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/tdb#171]
We have 3 options:
- Expose reactive counters through publications
- Count relations in a map transformation on the server, before sending the results down to clients
- Keep fields on MongoDB with counters, attach hooks on collections to update those fields and river those fields to ES. Then the search result array will have the counters as normal fields

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz

**Comment by lnmunhoz** [comment]
Option 3 is the best. The search is not reactive at all so we should send to ES the number os relations of the documents and update them on hooks like the other fields.

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz Precisa arrumar ainda? quer que eu arrume?

**Comment by lnmunhoz** [comment]
I created a solution for technologies but I think we should create a SimpleSchema extension to do this.

Something like this:
```js
{
  attachmentsId: {
    type: [String],
    esDriver: true,
  },
  attachmentsCount: {
    type: Number,
    esDriver: true,
    counterFor: 'attachmentsId' // Or something like that
  }
}
```
Then this `attachmentsCount` will  update on `after` hook getting the length of `attachmentsId`. The bad part is that we will have a single update operation for each property.

**Current solution**
I build a generic function that we can use on other models. Its currently like this:

```js
function generateCountersAfterUpdate(userId, doc) {
  const previousDoc = this.previous;
  const query = { _id: doc._id };
  let modifier = { $set: {}, $unset: {} };

  function setCountFor(property) {
    const entityName = property.replace('Id', '');
    const countingProperty = `${entityName}Count`;

    if (doc[property]) {
      if (!previousDoc[property] || previousDoc[property].length !== doc[property].length) {
        modifier.$set[countingProperty] = doc[property].length;
      }
    } else if (doc[countingProperty]) {
      modifier.$unset[countingProperty] = '';
    }
  }

  setCountFor('attachmentsId');
  setCountFor('projectsId');
  setCountFor('organizationsId');

  if (!_.isEmpty(modifier.$set) || !_.isEmpty(modifier.$unset)) {
    Technologies.update(query, modifier);
  }
}
```
This is just on `Technologies` for now

What you think about the SimpleSchema way @rafaelcorreiapoli?

**Comment by rafaelcorreiapoli** [comment]
### Projects About Box
- CollectionsCounter -> hook on insert and remove of collection "Collections", using $inc
- CollectionsSetCounter: hook on insert and remove of collection "CollectionsSet", using $inc
- TechnologiesStashCounter: using $inc on pushTechnologiesStash and pullTechnologiesStash methods
- TechnologiesStashReviewCounter: Since it's a dynamic counter, i'm publishing it as "project-tech-stash-review", with Counts package
