### ISSUE TITLE
Fix "active" class on topNavigation

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/tdb#173]

**Comment by lnmunhoz** [comment]
@rafaelcorreiapoli 
It is working already. Maybe you got confused because in tdb-design doesn't work.

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz I'm reopening this, please pay attention to what is happening:
There is a js script on Inspinia that activates the menu item ON CLICK
So if you access directly a route by it's address or access a subroute like /technologies/add, the menu item will not be highlighted

**Comment by rafaelcorreiapoli** [comment]
I've fixed it on my last commits

**Comment by lnmunhoz** [comment]
Nice. Closing...
