### ISSUE TITLE
Fix label colors on latest updates

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/tdb#175]

**Comment by rafaelcorreiapoli** [comment]
I've done it.
recentUpdatesItem will check if the collection is 'technologies', if it is, it will subscribe to the technology with this pub:
```technology.status``` which will retrieve the status
then it will draw the label with or without the icon (specified on the property hasIcon of the recentUpdates data)
If it's not from the 'technologies' collection, we draw a default label ('default' class from bootstrap)
