### ISSUE TITLE
projectCollection

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#179]
First push here 53c21d9856960b1cca7a606520869418e233042d

there are some fixes to be made:

ToDo

- [x] Autosize Collection columns according to subCollection number.
- [x] Crop Stash thumbnail Square
<img width="302" alt="screen shot 2016-04-04 at 3 47 37 pm" src="https://cloud.githubusercontent.com/assets/533339/14249963/98b8ced6-fa7c-11e5-8f2f-e8f0c396807d.png">

**Comment by rafaelcorreiapoli** [comment]
How do we create a Collection ?

**Comment by arthursoares** [comment]
Only name to start with. All editing is done via projects/collection view
On Fri, Apr 8, 2016 at 00:43 Rafael Ribeiro <notifications@github.com>
wrote:

> How do we create a Collection ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/179#issuecomment-207123375>
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by rafaelcorreiapoli** [comment]
- "Futuro da Medicina" is a project, that contains on it's technologieStash thse technologies:
"Aerogel", "Drone Delivery", "Selfie Security"
- "Taxonomy" is a collectionSet that contains this collections:
"IT & Systems" and "IT & Systems"
- "IT & Systems" (I) is a collection that contains one subCollection "Distribution"
- "IT & Systems" (II) is a collection that contains two subCollectiions, "Distribution" and "Production"
- "Production" is a subCollection that contains two technologies: "Drone Delivery" and "Other cool technology"

Are those afirmations correct?

**Comment by rafaelcorreiapoli** [comment]
Arthur, a lista na esquerda mostra as tecnologias no stash? 
O text input é para realizar uma busca dentro das stash?
Ao clicar no botão [+], qual o comportamento?

**Comment by arthursoares** [comment]
Yes! That is correct :-)
Sim, é para realizar busca no Stash. O + é para realizar busca
geral/adicionar Tech do db no Stash
On Fri, Apr 8, 2016 at 09:47 Rafael Ribeiro <notifications@github.com>
wrote:

> Arthur, a lista na esquerda mostra as tecnologias no stash?
> O text input é para realizar uma busca dentro das stash?
> Ao clicar no botão [+], qual o comportamento?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/179#issuecomment-207282258>
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by rafaelcorreiapoli** [comment]
Então, mas ela é feita na própria lista que serve para mostrar o stash? ou abre um Modal (hehehe) ou algo do tipo ?

Outra dúvida: uma mesma collection pode estar presente em mais de uma CollectionSet?

**Comment by arthursoares** [comment]
@rafaelcorreiapoli +1 ponto para Modal :)

Eu originalmente achava que não, ma sim. Porque poderemos em algum momento copiar uma Collection para outro projeto inclusive.

**Comment by rafaelcorreiapoli** [comment]
Arthur, uma duvida.
Quando algo é arrastado do techStash para uma collection, a tech não some do techStash né?

**Comment by arthursoares** [comment]
Isso, ela não some. Porque uma tech pode estar em mais de uma collection
também

On Sat, Apr 23, 2016 at 12:47 AM, Rafael Ribeiro <notifications@github.com>
wrote:

> Arthur, uma duvida.
> Quando algo é arrastado do techStash para uma collection, a tech não some
> do techStash né?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/179#issuecomment-213615724>
>



-- 
http://arthur.wtf
+55 11 96960.6666

**Comment by rafaelcorreiapoli** [comment]
Pode ter a mesma tech mais de uma vez na mesma collection ou stash? Isso iria complicar bastante as operações no mongo..
Mas quando arrasto de uma collection para outra ela some da collection origem?

**Comment by michellzappa** [comment]
Há possibilidade de simplesmente indicar se a tech já foi usada duas ou
mais vezes? Um ícone alerta, etc. Talvez seja a melhor solução.

**Comment by rafaelcorreiapoli** [comment]
@michellzappa, atualmente, quando você tenta dropar uma tech em uma subCollection em que já existe tal tech, nada acontece no banco de de dados e é mostrada uma mensagem de erro para o usuário através de um Toastr

**Comment by rafaelcorreiapoli** [comment]
@arthursoares @michellzappa: Muito importante:
A ordem em que as collections aparecem dentro de uma collectionSet, importa?
A ordem em que as sub collections aparecem dentro de uma collectionSet, importa?
A ordem em que as technologies aparecem dentro de uma subCollection, importa?

Se sim, teremos que fazer algumas mudanças aqui #7

**Comment by arthursoares** [comment]
Até agora, nos cenários que temos trabalhado, não importam. Em nenhuma das
3 situações :)

2016-04-26 2:57 GMT+02:00 Rafael Ribeiro <notifications@github.com>:

> @arthursoares <https://github.com/arthursoares> @michellzappa
> <https://github.com/michellzappa>: Muito importante:
> A ordem em que as collections aparecem dentro de uma collectionSet,
> importa?
> A ordem em que as sub collections aparecem dentro de uma collectionSet,
> importa?
> A ordem em que as technologies aparecem dentro de uma subCollection,
> importa?
>
> Se sim, teremos que fazer algumas mudanças aqui #7
> <https://github.com/envisioning/tdb/issues/7>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/179#issuecomment-214575901>
>



-- 
http://arthur.wtf
+55 11 96960.6666

**Comment by rafaelcorreiapoli** [comment]
Should we close this?
@arthursoares

**Comment by arthursoares** [comment]
Just one fix:

Switch the order of the buttons inside the techStash. The `+ Add` should come in the beginning/before the input box. As it is adding a technology to the stash.
