### ISSUE TITLE
projectDashboard

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#18]
Placeholder issue for further development.
Reserving the issue ID to link with the visual UX map.

**Comment by rafaelcorreiapoli** [comment]
@arthursoares, for now, should it be just like technologiesDashboard or organizationsDashboard? or should we wait for further development and design mockups?

**Comment by arthursoares** [comment]
Exactly like the other dashboards for now :)

**Comment by rafaelcorreiapoli** [comment]
Can we close this for now?

**Comment by arthursoares** [comment]
Yes
