### ISSUE TITLE
Classes names to make masonry work

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/tdb#191]
We are using these classes to make masonry work:
```card-box cards-item```
These classes are supposed to be on the card itself, not in the wrapping class of the cards on masonry context
We should move these classes to cards and create another classes to make masonry grid

**Comment by lnmunhoz** [comment]
I found a library that maybe can be used instead of masonry. Here: http://raphamorim.com/waterfall.js/. (Not tested yet)

**Comment by michellzappa** [comment]
@lucas Looks good to me.

**Comment by arthursoares** [comment]
Yep. Seems smaller/faster than masonry.

**Comment by arthursoares** [comment]
## This is only a test.

:) just trying something on GHI.

**Comment by lucas** [comment]
@michellzappa thanks for the info

**Comment by lnmunhoz** [comment]
Wrong Lucas! @michellzappa Haha

**Comment by lucas** [comment]
:)

**Comment by rafaelcorreiapoli** [comment]
Hahahahahaha


+1 for Waterfall
