### ISSUE TITLE
techStashTable

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/tdb#193]
![tdb_technologiesstashadd](https://cloud.githubusercontent.com/assets/12840136/14550656/e739cdfe-02a0-11e6-943b-fdc719818dec.png)
![tdb_2](https://cloud.githubusercontent.com/assets/12840136/14550658/ea106128-02a0-11e6-94ba-51e15615a089.png)

- [ ] Search Mechanism
- The modal to add to stash is ElasticSearch powered
- Delete needs confirmation
- Showing tech status and collections in real time
- [ ] fa fa-search, what does this button do?

**Comment by arthursoares** [comment]
You can ignore the `fa fa-search`. I think it was a placeholder. Let's just put regular CRUD operations.
