### ISSUE TITLE
projectEntry

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#20]
<img width="1202" alt="screen shot 2015-12-15 at 5 18 46 pm" src="https://cloud.githubusercontent.com/assets/533339/11821342/25803c20-a350-11e5-9754-496b62c99ee3.png">

- [ ] Add contextual actions to collections & subCollections
- [ ] Add support to Attachments.
- [ ] Documentation and settings.

**Comment by rafaelcorreiapoli** [comment]
![tdb_1](https://cloud.githubusercontent.com/assets/12840136/14550603/7229d158-02a0-11e6-9d95-d44e503b7930.png)

**Comment by arthursoares** [comment]
<3

**Comment by arthursoares** [comment]
Where can we test it?

**Comment by rafaelcorreiapoli** [comment]
It's on staging.
We need to add support for attachments
What is "Documentation and settings." ?
