### ISSUE TITLE
Fix projectDashboard: log and statistics

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#200]
<img width="1414" alt="screen shot 2016-05-02 at 9 38 24 am" src="https://cloud.githubusercontent.com/assets/533339/14949372/b0a14d60-1049-11e6-833c-ceebccfff94e.png">

Both the recent updates and the statistics box are showing wrong information.

**Comment by rafaelcorreiapoli** [comment]
I fixed the recentUpdates, it was without the projects filter
But I think that the statistics on the left panel are right, aren't they ?
