### ISSUE TITLE
projectEntry: collections CRUD operations not working (?)

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#201]
<img width="1026" alt="screen shot 2016-05-02 at 9 39 23 am" src="https://cloud.githubusercontent.com/assets/533339/14949386/d2da9e68-1049-11e6-9514-27dd6a8fae72.png">

Buttons in the box are not working

**Comment by rafaelcorreiapoli** [comment]
Eu não tinha muita certeza do que eles faziam, daí não programei nada ainda
- o primeiro é pra editar a descrição
- o segundo é para criar uma sub collection
- e o terceiro é para deletar

É isso?
