### ISSUE TITLE
projectAdd: Relations?

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#203]
<img width="1402" alt="screen shot 2016-05-02 at 9 44 12 am" src="https://cloud.githubusercontent.com/assets/533339/14949530/054e844e-104b-11e6-8edc-0e5c5c15c8bb.png">

Primary objective is to be able to add `organizations`. You can set it to the same way we have in `technologyAdd`, where you have an input box and add as tags.
`attachments` are not necessary when you're adding a new project.

**Comment by rafaelcorreiapoli** [comment]
Fixed.

**Comment by rafaelcorreiapoli** [comment]
Fixed
