### ISSUE TITLE
____Entry: after edit.

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#204]
After editing a `technology`, `project`, `organization`, `user` or `attachment`, user should be redirected to the `parent` page.

**Comment by rafaelcorreiapoli** [comment]
- [ ] Projects
- [ ] Technologies, @lnmunhoz Please fix this
- [ ] Organizations

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz Please do this quickfix so we can close

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz ping

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz is this fixed?

**Comment by lnmunhoz** [comment]
Done
