### ISSUE TITLE
collectionEntry: Remove page padding

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#206]
<img width="1440" alt="screen shot 2016-05-02 at 9 56 44 am" src="https://cloud.githubusercontent.com/assets/533339/14949682/357335ce-104c-11e6-876c-57efa1a2ec88.png">

This page works a lot better without the padding for those iBoxes.

**Comment by rafaelcorreiapoli** [comment]
The padding is not on the ibox itself, it is on the wrapper (on the page layout)
I will create a different layout that does not implements the wrapper

**Comment by arthursoares** [comment]
@rafaelcorreiapoli great!
