### ISSUE TITLE
technologyAdd: Fix label input

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#208]
<img width="564" alt="screen shot 2016-05-02 at 10 01 04 am" src="https://cloud.githubusercontent.com/assets/533339/14949767/d82f813c-104c-11e6-8395-bc7f84e36ac2.png">

Whenever we're adding an alternative Title or Tag, it is constrained within a fixed width. We should be able to see all the text while we type.

**Comment by lnmunhoz** [comment]
Done 6f091a9
