### ISSUE TITLE
technologyEdit: Description

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#209]
I'm disregarding the bugs in technologyAdd due to the changes set on the Friday meeting with @lnmunhoz (flow of adding new technology).

When I'm creating a new description, it won't allow me to `Save as Draft` or publish.

<img width="1029" alt="screen shot 2016-05-02 at 10 05 13 am" src="https://cloud.githubusercontent.com/assets/533339/14949857/a3d87262-104d-11e6-98ad-6631a8c59d68.png">

**Publish**: When I choose it, the modal doesn't respond on the `Yes` button
<img width="718" alt="screen shot 2016-05-02 at 10 05 08 am" src="https://cloud.githubusercontent.com/assets/533339/14949871/bf83cb6a-104d-11e6-99a2-76be010964d4.png">

**Save as draft**: I get this error.
<img width="366" alt="screen shot 2016-05-02 at 10 05 35 am" src="https://cloud.githubusercontent.com/assets/533339/14949880/c957a346-104d-11e6-8a37-60570ea7e061.png">

**Comment by lnmunhoz** [comment]
What technology is this @arthursoares?

**Comment by arthursoares** [comment]
@lnmunhoz latest one I've created.

**Comment by lnmunhoz** [comment]
That's awkward. It was the Chat UI? I tested and its everything ok on staging.

**Comment by arthursoares** [comment]
It was the Chat UI. Bug remains.
