### ISSUE TITLE
technologyEdit: Images "showcased"

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#211]
<img width="297" alt="screen shot 2016-05-02 at 10 10 59 am" src="https://cloud.githubusercontent.com/assets/533339/14949924/3ccfe590-104e-11e6-80af-6126607c52e4.png">

Checkbox is not working.

**Comment by lnmunhoz** [comment]
Now we have the new design

![demo](http://g.recordit.co/RdBswVWMK0.gif)
