### ISSUE TITLE
technologyEdit: Description and Save flow

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#212]
<img width="1425" alt="screen shot 2016-05-02 at 10 13 11 am" src="https://cloud.githubusercontent.com/assets/533339/14949984/9d767210-104e-11e6-8c59-c0e76d401731.png">

You should not be able to `Save` a technology while the `description` box is `unsaved`. 
While you're editing, the `Save` on the technology will be disabled, only after you `Save as Draft`, `Publish`, `Cancel` or `Delete` it will become Available again.

**Comment by lnmunhoz** [comment]
I think the `Save` button on the left should update just the technology status. The descriptions are updated in the moment you `Save as draft` or `Publish`, not when clicked on the `Save` on the left. Every change on the information are updated automatically, so why create a two steps save for descriptions? Makes sense?

**Comment by lnmunhoz** [comment]
Maybe I should wait for #214 to make any changes.
