### ISSUE TITLE
Projects API architecture upgrade

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/tdb#225]
Upgrade to the 1.3 API structure like technologies.

**Comment by rafaelcorreiapoli** [comment]
- [ ] Methods

**Comment by rafaelcorreiapoli** [comment]
# Collections Set
## server & common
- [ ] Methods
- [ ] Scehma
- [ ] MongoCollection
- [ ] Publications

## client
- [ ] UI Components
 - [ ] collectionsBoard
 - [ ] collectionsSetAdd
 - [ ] collectionsSetEntry
 - [ ] collectionsSetList

**Comment by rafaelcorreiapoli** [comment]
# Collections
## server & common
- [ ] Methods
- [ ] Scehma
- [ ] MongoCollection
- [ ] Publications

## client

**Comment by lnmunhoz** [comment]
@rafaelcorreiapoli Essa ultima parte deixa para fazermos juntos. Precisamos discutir algumas coisas.

**Comment by lnmunhoz** [comment]
Done for now. We will keep upgrading.
