### ISSUE TITLE
How to fix Autoform Window Scope Bug

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/tdb#230]
We will not put the collections on the window scope,
instead, we will create a TEMPLATE HELPER that returns an object that has pointers to all collections
I created a file called autoform_scope.js
There, I import all the Collections and register a function that returns the object with the name "Colletions"

**autoform_scope.js**
```js
import { Projects } from '../../api/projects/Projects';
import { Technologies } from '../../api/technologies/technologies';

let collections = {
  Projects,
  Technologies
};

Template.registerHelper('Collections', () => collections);
```

Then, in my autoforms:
**projects_edit.html**
```html
  {{#if Template.subscriptionsReady}}
    {{#autoForm 
      id="updateProjectsForm" 
      doc=organization 
      collection=Collections.Projects
      type="method-update" 
      meteormethod="projects.update" 
      class="form-horizontal" 
      singleMethodArgument=true}}

(...)
```

It's important to import this file before components.js

**index.js**
```js
import './autoform_scope.js';
import './components.js';
```

@lnmunhoz

**Comment by lnmunhoz** [comment]
Just create a helper on your template that uses autoform to return the collection reference. See technologies_edit or technologies_add.

**Comment by lnmunhoz** [comment]
I will close this ok?
