### ISSUE TITLE
Looping on new tab access

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/tdb#231]
![http://g.recordit.co/iIqI7iwmOY.gif](http://g.recordit.co/iIqI7iwmOY.gif)

**Comment by rafaelcorreiapoli** [comment]
Local não tá acontecendo né?

**Comment by rafaelcorreiapoli** [comment]
A master tá muito atrás da staging, vamos dar merge para ver se isso persiste

**Comment by rafaelcorreiapoli** [comment]
Não está acontecendo na staging. Acredito que algum bug da master desatualizada...

**Comment by arthursoares** [comment]
Aqui acontece na minha Staging também.

**Comment by arthursoares** [comment]
Seems good from here.
