### ISSUE TITLE
technologyStatus: Stars or Status

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#243]
This is an important ongoing discussion that we currently have two stances. I want to present some arguments in order to move forward with this issue. The matter of debate is about using `toggle status` (Draft, Review or Published) vs. `star rating system` to determine a technology Status.

I understand the arguments to move on to a star rating system, but I say that **for now** we stick with what we've designed and developed already, which is the Toggle Status. 

Here is why I think it is best for us.

* The star rating system worked well for the research flow that was adopted on Trello. Which is a lot different then ours at TDB. Trello is a much more horizontal structure. In a sense that every user has the same level of permission (at least users on our boards).
* On TDB, we have Users, Editors and Admins. Users may change and edit a description of a technology, but whenever they do, those will be created and saved only as `Drafts`. This requires the role of an `Editor`, who will _Edit_ the updates and decide if a technology should be updated or not. 
* Only Editors and Admins have privileges to save a technology as Published. 
* Also, only Editors and Admins have privileges to save a `technology description` as Published.
* This allows for us (envisioning) to have a better control of the editorial content of technologies at the moment. I believe that this is fundamental at the moment, as the first usage of the platform is to develop our researches.
* I think that a Star Rating system might lead to some big cognitive misunderstandings on the technology. A 4-star technology is better than a 5-star technology? What are we classifying? Just the description and content of the technology or the technology itself? This will create some unwanted noise.

I say that for now, at least for this first period of Closed beta, we stick with the Toggle selection and see how it goes. If it flunks and we see the need, we'll work a better way to implement the stars. But right now, I see no value in debunking something that we haven't even tested yet.

@michellzappa

_Referencing to other discussions and #205_

**Comment by michellzappa** [comment]
OK, let's keep current solution.

**Comment by thiaracavadas** [comment]
agreed

**Comment by arthursoares** [comment]
Good. We'll stick with the existing scheme.
