### ISSUE TITLE
technologyAdd: Image thumbnail is not working

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#260]
The end point of the URL (after upload) is broken:
`https://res.cloudinary.com/envisioning/image/upload/c_fill,g_center,h_180,w_180/v1/s3-production/images/nFx2zuhCnmnye5wte`

<img width="825" alt="screen shot 2016-05-13 at 12 05 03 pm" src="https://cloud.githubusercontent.com/assets/533339/15244774/1a3c7c38-1903-11e6-8abe-840f2401f0a3.png">

**Comment by rafaelcorreiapoli** [comment]
@lnmunhoz A pasta para o qual estavam sendo upados os arquivos era a pasta "tdb"
no Cloudinary, a gente tem um mapeamento "s3" -> "tdb" e um mapeamento "s3-production" -> "tdb-production"
O cliente estava tentando consultando a pasta "s3-production" do Cloudinary para fazer o download das imagens passando pelo sistema de transformations do Cloudinary
o que está errado pois s3-production mapeia pra tdb-production, sendo que a pasta para qual as imagens estavam sendo enviadas era a "tdb", nao a "tdb-production"
Em resumo:
mudei a o s3mapping (no METEOR_SETTINGS) que ele acessa do cloudinary para a pasta "s3" ao invez de "s3-production"

**Comment by lnmunhoz** [comment]
Ok! Por favor deixa o settings-production atualizado pois no próximo builld
ele será usado como referência.

Obrigado :)

Em sex, 13 de mai de 2016 18:12, Rafael Ribeiro <notifications@github.com>
escreveu:

> @lnmunhoz <https://github.com/lnmunhoz> A pasta para o qual estavam sendo
> upados os arquivos era a pasta "tdb"
> no Cloudinary, a gente tem um mapeamento "s3" -> "tdb" e um mapeamento
> "s3-production" -> "tdb-production"
> O cliente estava tentando consultando a pasta "s3-production" do
> Cloudinary para fazer o download das imagens passando pelo sistema de
> transformations do Cloudinary
> o que está errado pois s3-production mapeia pra tdb-production, sendo que
> a pasta para qual as imagens estavam sendo enviadas era a "tdb", nao a
> "tdb-production"
> Em resumo:
> mudei a o s3mapping (no METEOR_SETTINGS) que ele acessa do cloudinary para
> a pasta "s3" ao invez de "s3-production"
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/tdb/issues/260#issuecomment-219160551>
>
-- 
Best,
Lucas
http://lucasmunhoz.com

**Comment by lnmunhoz** [comment]
Fixed settings fe18e37
