### ISSUE TITLE
technologyDashboard - Recent Update: Change behavior of click

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#273]
<img width="1022" alt="screen shot 2016-05-20 at 2 08 46 pm" src="https://cloud.githubusercontent.com/assets/533339/15427306/72150e2a-1e94-11e6-9554-59ec1e6a0218.png">

When you click on a technology, it leads you to `edit`, should take you to `entry` instead.

**Comment by arthursoares** [comment]
**Edit**: I've changed the title. Apparently every link to a technology is going to the `Edit` and not to the `Entry` screen.

**Comment by lnmunhoz** [comment]
Yes. I will take care of this.

**Comment by rafaelcorreiapoli** [comment]
Fixed here a98cab75bc4f88de5bda809160a4c84d5ef4ce33
