### ISSUE TITLE
attachmentCard: Link error

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#274]
<img width="306" alt="screen shot 2016-05-20 at 3 00 27 pm" src="https://cloud.githubusercontent.com/assets/533339/15428435/a0b3b1f8-1e9b-11e6-9800-9339caeab16c.png">

The image has the correct URL, but the title doesn't.

**Comment by rafaelcorreiapoli** [comment]
Fixed here 6733acb5c84cf15e9f2ba6ba50b929c08fda701b
