### ISSUE TITLE
attachmentEntry: deprecated layout

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#276]
<img width="510" alt="screen shot 2016-05-20 at 3 03 24 pm" src="https://cloud.githubusercontent.com/assets/533339/15428505/092357c0-1e9c-11e6-8721-7a9a2b667676.png">

It should follow the other `entry` (tech, etc…) templates.

**Comment by rafaelcorreiapoli** [comment]
![attachments entry](https://cloud.githubusercontent.com/assets/12840136/15440738/7d472684-1ead-11e6-9e0d-430bab6f7fc9.png)

**Comment by arthursoares** [comment]
- [ ] Missing CRUD operation. (Edit button / Delete)
