### ISSUE TITLE
recentUpdates: Clicking on an user handler leads to 404

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#277]
<img width="615" alt="screen shot 2016-05-20 at 4 48 12 pm" src="https://cloud.githubusercontent.com/assets/533339/15431546/b109ce20-1eaa-11e6-96cf-ae8f9b01c6f9.png">

Clicking on "Arthur Soares"  leads me to `https://tdb.envisioning.io/users/entry`

**Comment by rafaelcorreiapoli** [comment]
Fixed d226857cdfd77cd1af6e3516917e78796274f515
