### ISSUE TITLE
organizationEntry: List are still being used. Deprecated design.

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#285]
<img width="1053" alt="screen shot 2016-05-23 at 3 45 49 pm" src="https://cloud.githubusercontent.com/assets/533339/15472869/7b0e3928-20fd-11e6-9a88-91c8d37faaf3.png">

Where is the card layout?

**Comment by rafaelcorreiapoli** [comment]
![new org](https://cloud.githubusercontent.com/assets/12840136/15517406/f94816ee-21cd-11e6-8ee1-8e71a436b563.png)

@arthursoares, Nestes layouts em que desenhamos os cards, devemos esconder o "tools" deles? (aquele icone no canto superior esquerdo)
Pois ele tem uma ação que é: "Delete Attachment" por exemplo e o usuário pode vir a entender que este botão serve para remover o attachment da organizations, quando na verdade esse botão serve para deletar o próprio attachment do banco de dados.

**Comment by arthursoares** [comment]
Sim! A ideia dos cards era para que esses `tools` tivessem funções diferentes que variam de acordo com o contexto, mas ainda não fizemos isso :)
