### ISSUE TITLE
userName on Toolbar links to userEntry

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#291]
:)

<img width="247" alt="screen shot 2016-05-23 at 4 13 07 pm" src="https://cloud.githubusercontent.com/assets/533339/15476773/588bcb86-2111-11e6-9e04-bafbfc7f60d9.png">

**Comment by rafaelcorreiapoli** [comment]
Arthur, isto já estava implementado, eu acho que você não estava vendo pois seu user não tinha nome/sobrenome.
Após #81, isto não será mais um problema
