### ISSUE TITLE
UX Views

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#30]
![tdb uxoverview](https://cloud.githubusercontent.com/assets/533339/11757449/8baefb86-a048-11e5-897d-16011f47851d.png)

* v1. This is the first draft for the overall UX screens on TDB.

### General

- [ ] #14 Login
- [ ] #15 mainDashboard

### Technology

- [ ] #16 techDashboard
- [ ] #17 techEntry
- [ ] #12 techList

### Project

- [ ] #18 projectDashboard
- [ ] #19 projectList
- [ ] #20 projectEntry
- [ ] #21 godzillaExport
- [ ] #13 projectCollections
- [ ] #23 projectStash

### User

- [ ] #24 userDashboard
- [ ] #25 userEntry

### Organization

- [ ] #26 orgDashboard
- [ ] #27 orgEntry

### Attachment

- [ ] #28 attachmentDashboard
- [ ] #29 attachmentEntry

**Comment by arthursoares** [comment]
@lnmunhoz  @rafaelcorreiapoli let's stick with this document for screens and elements?

**Comment by rafaelcorreiapoli** [comment]
Ok! should I add the newly created Componentes/screens to this list?

**Comment by arthursoares** [comment]
Yes! Feel free to edit
On Sun, Jan 10, 2016 at 00:32 Rafael Ribeiro <notifications@github.com>
wrote:

> Ok! should I add the newly created Componentes/screens to this list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/30#issuecomment-170301559>.
>
-- 
+55 11 96960.6666
http://arthur.wtf
