### ISSUE TITLE
Image bug?

### ISSUE THREAD

**Issue by michellzappa** [envisioning/tdb#329]
![screen shot 2016-06-03 at 11 52 03](https://cloud.githubusercontent.com/assets/5923523/15782692/ab6d9aaa-2981-11e6-82a1-a61226e94163.png)
![screen shot 2016-06-03 at 11 52 10](https://cloud.githubusercontent.com/assets/5923523/15782694/ad76fd28-2981-11e6-81eb-25d34ce602f8.png)

**Comment by arthursoares** [comment]
Listed on #311 already.
