### ISSUE TITLE
Balsamiq Files

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/tdb#40]
Just for sharing Balsamiq projects and files.

**Comment by lnmunhoz** [comment]
[Techdb.bmpr.zip](https://github.com/envisioning/techdb/files/83859/Techdb.bmpr.zip)

**Comment by NDuma** [comment]
#### E-Mail Answered
Envisioning Collaborators now have access to a Desktop License through Balsamiq's Open Source initiatives.
![screenshot_3](https://cloud.githubusercontent.com/assets/8163869/12554546/eff38ab0-c331-11e5-883b-a5badfe14dec.png)

**Comment by lnmunhoz** [comment]
How to use this license? @arthursoares

**Comment by arthursoares** [comment]
@NDuma can you share the license with us?

**Comment by NDuma** [comment]
The previous statement may have been boisterous; we have available only 10.

Currently, [UserName]@envisioning.io emails have access for requests here:
https://docs.google.com/spreadsheets/d/1ZrQqnJf89-SicPp6y2wadzCQeDyU6b87ldygRUiSvRQ

@lnmunhoz @arthursoares for license privacy & tracking reasons myself or @michellzappa can facilitate there.

**Comment by arthursoares** [comment]
@NDuma can you issue a license for my e-mail? as@envisioning.io?

**Comment by NDuma** [comment]
@arthursoares Done! Check inbox. :smile: :+1:

**Comment by lnmunhoz** [comment]
Can we have a license? @arthursoares maybe for developers@envisioning.io or other email that we can use, please.

**Comment by NDuma** [comment]
@lnmunhoz ping me here: nd@envisioning.io

**Comment by NDuma** [comment]
@lnmunhoz @rafaelcorreiapoli Both sent now!

**Comment by lnmunhoz** [comment]
@NDuma Where to get the license key?

![Screenshot%202016-03-03%2012.17.13.png](https://photos-5.dropbox.com/t/2/AABtB2UPv8D-F9lC-DQ7EbOybesqjGTCPWcj4eUuhlXyiA/12/114088886/png/32x32/3/1457035200/0/2/Screenshot%202016-03-03%2012.17.13.png/ENDkiFgY6fkCIAcoBw/VXRcVwfbywkbRHaToLGzH14Et2TDJ7sSY_GjBsPnLQk?size_mode=3&size=1024x768)

**Comment by NDuma** [comment]
@lnmunhoz it should be in your e-mail - 
from:	Nick Dumas <nd@envisioningtech.com>
to:	lnmunhoz <ln.munhoz@gmail.com>
date:	Sun, Feb 28, 2016 at 8:35 PM

**Comment by lnmunhoz** [comment]
I didn't receive anything :(

**Comment by NDuma** [comment]
@lnmunhoz was on a conference call; I responded & fwded to the message you sent me.

**Comment by lnmunhoz** [comment]
There's no license here

Em qui, 3 de mar de 2016 às 17:25, NDuma <notifications@github.com>
escreveu:

**Comment by NDuma** [comment]
@lnmunhoz I'd like to avoid posting it in public. If you've found the e-mails it is contained in the first response to your message on Feb 28th.
Do you have another preferred method for communicating?

**Comment by lnmunhoz** [comment]
Yes. Shoot me at lucas.nmunhoz@hotmail.com

Em qui, 3 de mar de 2016 às 17:38, NDuma <notifications@github.com>
escreveu:

**Comment by lnmunhoz** [comment]
@NDuma I just founded! It was in another conversation. My mistake!
Thank you

Em qui, 3 de mar de 2016 às 17:51, lnmunhoz <ln.munhoz@gmail.com> escreveu:
