### ISSUE TITLE
Fix SSL Certificate for tdb.envisioning.io

### ISSUE THREAD

**Issue by michellzappa** [envisioning/tdb#64]
Is this something I can do?

**Comment by arthursoares** [comment]
Perhaps, we need to purchase an SSL certificate from gandi.net for wildcard domains
https://www.gandi.net/ssl/standard#wildcard

**Comment by arthursoares** [comment]
@michellzappa

**Comment by michellzappa** [comment]
Why Wildcard and not Single Address? (10x price difference)

**Comment by arthursoares** [comment]
@lnmunhoz @rafaelcorreiapoli we have a fixed IP address for TDB, right? Can you send it to @michellzappa?

**Comment by lnmunhoz** [comment]
The endpoint is https://tdb-58442.onmodulus.net/.

**Comment by lnmunhoz** [comment]
SSL Guide: https://help.modulus.io/customer/portal/articles/1701165-ssl-setup-guide

**Comment by michellzappa** [comment]
@lnmunhoz Can you generate a CSR for our Modulus installation? I can then use this to purchase certificate.

**Comment by michellzappa** [comment]
@lnmunhoz Also, what should we select for "Software" ?

![screenshot 2016-03-09 12 08 16](https://cloud.githubusercontent.com/assets/5923523/13639465/a07c4e0a-e5ef-11e5-9f93-bd479d5cd0ed.png)

**Comment by arthursoares** [comment]
@lnmunhoz

**Comment by michellzappa** [comment]
Ping. I can only configure SSL certificate with a generated CSR. @lnmunhoz

**Comment by michellzappa** [comment]
Unless I can generate that myself. But it doesn't seem to be the case.

**Comment by lnmunhoz** [comment]
@michellzappa Sorry, I will take a look.

**Comment by lnmunhoz** [comment]
I recommend this use [expeditedssl addon](https://addons.modulus.io/expeditedssl) from modulus. Is to expensive?

**Comment by michellzappa** [comment]
Will this SSL add-on do everything we need for $15/month, or do we need
additional modules?

**Comment by lnmunhoz** [comment]
I think $15 will do all the job.

**Comment by michellzappa** [comment]
Open/Free SSL certificate host option: https://letsencrypt.org/certificates/
